# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Saitama' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Saitama
  pod 'ChameleonFramework/Swift'
  pod 'MBProgressHUD'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'EZAlertController'
  pod 'BFKit-Swift'
  pod 'GoogleMaps'

  target 'SaitamaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SaitamaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
